-- Typed models for the MemesioContentCreation SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Agent
---@field description? string
---@field locale? string
---@field name string
---@field slug? string
---@field status? string
---@field stylePreset? string
---@field systemPrompt? string
---@field watermarkText? string
---@field websiteUrl? string

---@class AgentLoadMatch
---@field id? string

---@class AgentCreateData
---@field description? string
---@field locale? string
---@field name string
---@field slug? string
---@field status? string
---@field stylePreset? string
---@field systemPrompt? string
---@field watermarkText? string
---@field websiteUrl? string

---@class AgentUpdateData
---@field id string
---@field description? string
---@field locale? string
---@field name? string
---@field slug? string
---@field status? string
---@field stylePreset? string
---@field systemPrompt? string
---@field watermarkText? string
---@field websiteUrl? string

---@class AgentInfra
---@field action string
---@field chatId string
---@field memeSlug string
---@field metadata? table
---@field payoutReference? string
---@field payoutStatus? string
---@field phoneOrChatId string
---@field prompt string
---@field proof? table
---@field quotaBoostPerDay? number
---@field scopes? table
---@field userId? string
---@field weekStart? string

---@class AgentInfraLoadMatch
---@field action? string
---@field chatId? string
---@field memeSlug? string
---@field metadata? table
---@field payoutReference? string
---@field payoutStatus? string
---@field phoneOrChatId? string
---@field prompt? string
---@field proof? table
---@field quotaBoostPerDay? number
---@field scopes? table
---@field userId? string
---@field weekStart? string

---@class AgentInfraCreateData
---@field agent_id? string
---@field unlock_id? string
---@field action string
---@field chatId string
---@field memeSlug string
---@field metadata? table
---@field payoutReference? string
---@field payoutStatus? string
---@field phoneOrChatId string
---@field prompt string
---@field proof? table
---@field quotaBoostPerDay? number
---@field scopes? table
---@field userId? string
---@field weekStart? string

---@class AgentInfraRemoveMatch
---@field agent_id string
---@field key_id string

---@class AiCaption
---@field blockedTerms? table
---@field canvasText table
---@field captionCount? number
---@field captionSets? table
---@field entities? table
---@field fallbackUsed? boolean
---@field generationStrategy? string
---@field locale? string
---@field memeId? string
---@field memeSlug? string
---@field name string
---@field ok? boolean
---@field optionCount? number
---@field ownerToken? string
---@field providerId? string
---@field referenceCaptions? table
---@field rewriteNote? string
---@field sceneSummary? string
---@field templateDescription? string
---@field templateName? string
---@field templateTags? table
---@field tone string
---@field toneCues? table
---@field trendKeywords? table
---@field trendReferences? table
---@field trendSignals? table
---@field variationOffset? number
---@field voiceRules? table

---@class AiCaptionLoadMatch
---@field blockedTerms? table
---@field canvasText? table
---@field captionCount? number
---@field captionSets? table
---@field entities? table
---@field fallbackUsed? boolean
---@field generationStrategy? string
---@field locale? string
---@field memeId? string
---@field memeSlug? string
---@field name? string
---@field ok? boolean
---@field optionCount? number
---@field ownerToken? string
---@field providerId? string
---@field referenceCaptions? table
---@field rewriteNote? string
---@field sceneSummary? string
---@field templateDescription? string
---@field templateName? string
---@field templateTags? table
---@field tone? string
---@field toneCues? table
---@field trendKeywords? table
---@field trendReferences? table
---@field trendSignals? table
---@field variationOffset? number
---@field voiceRules? table

---@class AiCaptionCreateData
---@field blockedTerms? table
---@field canvasText table
---@field captionCount? number
---@field captionSets? table
---@field entities? table
---@field fallbackUsed? boolean
---@field generationStrategy? string
---@field locale? string
---@field memeId? string
---@field memeSlug? string
---@field name string
---@field ok? boolean
---@field optionCount? number
---@field ownerToken? string
---@field providerId? string
---@field referenceCaptions? table
---@field rewriteNote? string
---@field sceneSummary? string
---@field templateDescription? string
---@field templateName? string
---@field templateTags? table
---@field tone string
---@field toneCues? table
---@field trendKeywords? table
---@field trendReferences? table
---@field trendSignals? table
---@field variationOffset? number
---@field voiceRules? table

---@class AiJob
---@field action string
---@field actorId? string
---@field afterState? table
---@field attempts? number
---@field beforeState? table
---@field brushEdits? table
---@field capability string
---@field celebrityConfidence? number
---@field consentAttested? boolean
---@field createdAt? string
---@field detectedFaceCount number
---@field edgeRefinement? number
---@field estimatedCostUsd? number
---@field frameTimeMs? number
---@field height number
---@field id string
---@field input? table
---@field layerId string
---@field layerType? string
---@field maxAttempts? number
---@field maxFaces? number
---@field mediaType? string
---@field metadata? table
---@field nsfwScore? number
---@field output? table
---@field projectId string
---@field providerId? string
---@field reason? string
---@field runAfterMs? number
---@field sourceAssetUrl string
---@field sourceFaceIndex? number
---@field sourceImageUrl string
---@field status string
---@field targetAssetUrl string
---@field targetFaceIndex? number
---@field timeoutMs? number
---@field traceId? string
---@field updatedAt? string
---@field versionId? string
---@field width number
---@field workerId string
---@field workspaceId? string

---@class AiJobLoadMatch
---@field id? string

---@class AiJobCreateData
---@field job_id? string
---@field action string
---@field actorId? string
---@field afterState? table
---@field attempts? number
---@field beforeState? table
---@field brushEdits? table
---@field capability string
---@field celebrityConfidence? number
---@field consentAttested? boolean
---@field createdAt? string
---@field detectedFaceCount number
---@field edgeRefinement? number
---@field estimatedCostUsd? number
---@field frameTimeMs? number
---@field height number
---@field id string
---@field input? table
---@field layerId string
---@field layerType? string
---@field maxAttempts? number
---@field maxFaces? number
---@field mediaType? string
---@field metadata? table
---@field nsfwScore? number
---@field output? table
---@field projectId string
---@field providerId? string
---@field reason? string
---@field runAfterMs? number
---@field sourceAssetUrl string
---@field sourceFaceIndex? number
---@field sourceImageUrl string
---@field status string
---@field targetAssetUrl string
---@field targetFaceIndex? number
---@field timeoutMs? number
---@field traceId? string
---@field updatedAt? string
---@field versionId? string
---@field width number
---@field workerId string
---@field workspaceId? string

---@class AiMemeGenerationSucceeded
---@field allowHeuristicFallback? boolean
---@field captionSource? string
---@field captions? table
---@field correlationId? string
---@field degradedFromAsync? boolean
---@field editableCaptions? table
---@field flow string
---@field imageUrl? string
---@field mode string
---@field ok boolean
---@field preferredProviderId? string
---@field prompt string
---@field rewriteNote? string
---@field runId? string
---@field status string
---@field templateId? string
---@field tone? string
---@field toneCues? table
---@field variantCount number
---@field variants table
---@field workspaceId? string

---@class AiMemeGenerationSucceededCreateData
---@field allowHeuristicFallback? boolean
---@field captionSource? string
---@field captions? table
---@field correlationId? string
---@field degradedFromAsync? boolean
---@field editableCaptions? table
---@field flow string
---@field imageUrl? string
---@field mode string
---@field ok boolean
---@field preferredProviderId? string
---@field prompt string
---@field rewriteNote? string
---@field runId? string
---@field status string
---@field templateId? string
---@field tone? string
---@field toneCues? table
---@field variantCount number
---@field variants table
---@field workspaceId? string

---@class AiProvider
---@field actorId? string
---@field correlationId? string
---@field limit? number
---@field mappingMode? string
---@field maxSlots? number
---@field prompt string
---@field sourceImageUrl string
---@field texts? table
---@field trendSignals? table
---@field workspaceId? string

---@class AiProviderLoadMatch
---@field actorId? string
---@field correlationId? string
---@field limit? number
---@field mappingMode? string
---@field maxSlots? number
---@field prompt? string
---@field sourceImageUrl? string
---@field texts? table
---@field trendSignals? table
---@field workspaceId? string

---@class AiProviderCreateData
---@field actorId? string
---@field correlationId? string
---@field limit? number
---@field mappingMode? string
---@field maxSlots? number
---@field prompt string
---@field sourceImageUrl string
---@field texts? table
---@field trendSignals? table
---@field workspaceId? string

---@class Analytics

---@class AnalyticsLoadMatch

---@class Auth
---@field displayName? string
---@field email string
---@field password string

---@class AuthCreateData
---@field displayName? string
---@field email string
---@field password string

---@class Billing

---@class BillingLoadMatch

---@class Collaboration
---@field authorId? string
---@field message string
---@field projectId string

---@class CollaborationLoadMatch
---@field authorId? string
---@field message? string
---@field projectId? string

---@class CollaborationCreateData
---@field authorId? string
---@field message string
---@field projectId string

---@class Compliance

---@class ComplianceLoadMatch

---@class CreateMeme
---@field canvas table
---@field captions table
---@field generationRunId? string|nil
---@field generationVariantId? string|nil
---@field imageDataUrl string
---@field overlays? table
---@field sourceImageUrl string
---@field templateSlug? string
---@field title? string
---@field visibility? string
---@field watermark table

---@class CreateMemeCreateData
---@field canvas table
---@field captions table
---@field generationRunId? string|nil
---@field generationVariantId? string|nil
---@field imageDataUrl string
---@field overlays? table
---@field sourceImageUrl string
---@field templateSlug? string
---@field title? string
---@field visibility? string
---@field watermark table

---@class DeveloperApi
---@field limit? number
---@field prompt string
---@field trendSignals? table

---@class DeveloperApiLoadMatch
---@field limit? number
---@field prompt? string
---@field trendSignals? table

---@class DeveloperApiCreateData
---@field limit? number
---@field prompt string
---@field trendSignals? table

---@class FreeCaptionMemeSuccess
---@field captions table
---@field templateSlug string
---@field title? string
---@field visibility? string
---@field watermark? table

---@class FreeCaptionMemeSuccessCreateData
---@field captions table
---@field templateSlug string
---@field title? string
---@field visibility? string
---@field watermark? table

---@class FreeTemplateSearch
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount number
---@field captionCount number
---@field captions table
---@field description string
---@field durationMs? number|nil
---@field exampleImageUrl? string|nil
---@field frameCount? number|nil
---@field height number|nil
---@field id string
---@field imageUrl string
---@field mediaType string
---@field name string
---@field posterImageUrl? string
---@field qualityStatus? string
---@field slug string
---@field sourceTemplateId string|nil
---@field sourceUrl? string
---@field tags? table
---@field width number|nil

---@class FreeTemplateSearchListMatch
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions? table
---@field description? string
---@field durationMs? number|nil
---@field exampleImageUrl? string|nil
---@field frameCount? number|nil
---@field height? number|nil
---@field id? string
---@field imageUrl? string
---@field mediaType? string
---@field name? string
---@field posterImageUrl? string
---@field qualityStatus? string
---@field slug? string
---@field sourceTemplateId? string|nil
---@field sourceUrl? string
---@field tags? table
---@field width? number|nil

---@class Generate
---@field base64? string
---@field byteLength number
---@field captions? table
---@field dataUrl? string
---@field delayMs number
---@field durationMs? number
---@field filename string
---@field fps? number
---@field gifSlug string
---@field height number
---@field mimeType string
---@field pages number
---@field parameters table
---@field returnBase64? boolean
---@field sourceDurationMs number
---@field startMs? number
---@field tags? table
---@field title? string
---@field width number
---@field widthPx? number

---@class GenerateCreateData
---@field base64? string
---@field byteLength number
---@field captions? table
---@field dataUrl? string
---@field delayMs number
---@field durationMs? number
---@field filename string
---@field fps? number
---@field gifSlug string
---@field height number
---@field mimeType string
---@field pages number
---@field parameters table
---@field returnBase64? boolean
---@field sourceDurationMs number
---@field startMs? number
---@field tags? table
---@field title? string
---@field width number
---@field widthPx? number

---@class Growth
---@field accountId? string
---@field action string
---@field actorId? string
---@field caption? string
---@field code? string
---@field externalAccountId? string
---@field handle? string
---@field limit? number
---@field logExposure? boolean
---@field memeSlug? string
---@field now? string
---@field platform? string
---@field profiles? table
---@field shareSlug? string
---@field surface? string
---@field weekStart? string

---@class GrowthLoadMatch
---@field accountId? string
---@field action? string
---@field actorId? string
---@field caption? string
---@field code? string
---@field externalAccountId? string
---@field handle? string
---@field limit? number
---@field logExposure? boolean
---@field memeSlug? string
---@field now? string
---@field platform? string
---@field profiles? table
---@field shareSlug? string
---@field surface? string
---@field weekStart? string

---@class GrowthCreateData
---@field accountId? string
---@field action string
---@field actorId? string
---@field caption? string
---@field code? string
---@field externalAccountId? string
---@field handle? string
---@field limit? number
---@field logExposure? boolean
---@field memeSlug? string
---@field now? string
---@field platform? string
---@field profiles? table
---@field shareSlug? string
---@field surface? string
---@field weekStart? string

---@class ListMeme
---@field altText string
---@field canonicalImageUrl string
---@field createdAt string
---@field imageUrl string
---@field nsfwStatus string
---@field shareSlug string
---@field shareUrl string
---@field shareViews number
---@field slug string
---@field tags table
---@field templateSlug string
---@field title string
---@field visibility string

---@class ListMemeListMatch
---@field altText? string
---@field canonicalImageUrl? string
---@field createdAt? string
---@field imageUrl? string
---@field nsfwStatus? string
---@field shareSlug? string
---@field shareUrl? string
---@field shareViews? number
---@field slug? string
---@field tags? table
---@field templateSlug? string
---@field title? string
---@field visibility? string

---@class Media
---@field action string
---@field contentType? string
---@field expiresInSeconds? number
---@field ownerToken? string
---@field path? string
---@field prefix? string

---@class MediaCreateData
---@field action string
---@field contentType? string
---@field expiresInSeconds? number
---@field ownerToken? string
---@field path? string
---@field prefix? string

---@class Meme
---@field altText string
---@field canonicalImageUrl string
---@field canvas table
---@field captions table
---@field createdAt string
---@field imageUrl string
---@field nsfwStatus string
---@field overlays table
---@field shareSlug string
---@field shareUrl string
---@field shareViews number
---@field slug string
---@field sourceImageUrl string
---@field tags table
---@field templateSlug string
---@field title string
---@field visibility string
---@field watermark table

---@class MemeLoadMatch
---@field id string

---@class MemeRemoveMatch
---@field id string

---@class PublicTemplateMediaItem
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions table
---@field categories? table
---@field description string
---@field durationMs? number|nil
---@field exampleImageUrl? string|nil
---@field frameCount? number|nil
---@field height number|nil
---@field id string
---@field imageUrl string
---@field mediaType string
---@field name string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field slug string
---@field sourceTemplateId string|nil
---@field sourceUrl? string
---@field tags table
---@field width number|nil

---@class PublicTemplateMediaItemLoadMatch
---@field slug string

---@class StandaloneAgentBootstrap
---@field description? string
---@field handle string
---@field locale? string
---@field name string
---@field stylePreset? string
---@field systemPrompt? string
---@field watermarkText? string
---@field websiteUrl? string

---@class StandaloneAgentBootstrapCreateData
---@field description? string
---@field handle string
---@field locale? string
---@field name string
---@field stylePreset? string
---@field systemPrompt? string
---@field watermarkText? string
---@field websiteUrl? string

---@class Template
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions? table
---@field categories? table
---@field description string
---@field durationMs? number
---@field exampleImageUrl? string|nil
---@field fps? number
---@field frameCount? number|nil
---@field gifSlug? string
---@field height number|nil
---@field id string
---@field imageUrl string
---@field mediaType string
---@field name string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field returnBase64? boolean
---@field slug string
---@field sourceTemplateId string|nil
---@field sourceUrl? string
---@field startMs? number
---@field tags? table
---@field title? string
---@field width number|nil
---@field widthPx? number

---@class TemplateListMatch
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions? table
---@field categories? table
---@field description? string
---@field durationMs? number
---@field exampleImageUrl? string|nil
---@field fps? number
---@field frameCount? number|nil
---@field gifSlug? string
---@field height? number|nil
---@field id? string
---@field imageUrl? string
---@field mediaType? string
---@field name? string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field returnBase64? boolean
---@field slug? string
---@field sourceTemplateId? string|nil
---@field sourceUrl? string
---@field startMs? number
---@field tags? table
---@field title? string
---@field width? number|nil
---@field widthPx? number

---@class TemplateCreateData
---@field slug string
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions? table
---@field categories? table
---@field description string
---@field durationMs? number
---@field exampleImageUrl? string|nil
---@field fps? number
---@field frameCount? number|nil
---@field gifSlug? string
---@field height number|nil
---@field id string
---@field imageUrl string
---@field mediaType string
---@field name string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field returnBase64? boolean
---@field sourceTemplateId string|nil
---@field sourceUrl? string
---@field startMs? number
---@field tags? table
---@field title? string
---@field width number|nil
---@field widthPx? number

---@class TemplateSearch
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions table
---@field categories? table
---@field description string
---@field durationMs? number|nil
---@field exampleImageUrl? string|nil
---@field frameCount? number|nil
---@field height number|nil
---@field id string
---@field imageUrl string
---@field mediaType string
---@field name string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field slug string
---@field sourceTemplateId string|nil
---@field sourceUrl? string
---@field tags table
---@field width number|nil

---@class TemplateSearchListMatch
---@field animated? boolean
---@field assetBytes? number|nil
---@field assetContentType? string
---@field boxCount? number
---@field captionCount? number
---@field captions? table
---@field categories? table
---@field description? string
---@field durationMs? number|nil
---@field exampleImageUrl? string|nil
---@field frameCount? number|nil
---@field height? number|nil
---@field id? string
---@field imageUrl? string
---@field mediaType? string
---@field name? string
---@field posterImageUrl? string
---@field previewImageUrl? string
---@field qualityStatus? string
---@field slug? string
---@field sourceTemplateId? string|nil
---@field sourceUrl? string
---@field tags? table
---@field width? number|nil

---@class TrendAlert
---@field action string
---@field actorId string
---@field aggressiveness? number
---@field alertId string
---@field channels? table
---@field deliverAllAlerts? boolean
---@field event? table
---@field explicitNiches? table
---@field explicitRegions? table
---@field explicitSources? table
---@field explicitTopics? table
---@field followerCount? number
---@field niche? string
---@field region? string
---@field source? string
---@field topic string

---@class TrendAlertLoadMatch
---@field action? string
---@field actorId? string
---@field aggressiveness? number
---@field alertId? string
---@field channels? table
---@field deliverAllAlerts? boolean
---@field event? table
---@field explicitNiches? table
---@field explicitRegions? table
---@field explicitSources? table
---@field explicitTopics? table
---@field followerCount? number
---@field niche? string
---@field region? string
---@field source? string
---@field topic? string

---@class TrendAlertCreateData
---@field action string
---@field actorId string
---@field aggressiveness? number
---@field alertId string
---@field channels? table
---@field deliverAllAlerts? boolean
---@field event? table
---@field explicitNiches? table
---@field explicitRegions? table
---@field explicitSources? table
---@field explicitTopics? table
---@field followerCount? number
---@field niche? string
---@field region? string
---@field source? string
---@field topic string

---@class UploadCaptionMemeSuccess

---@class UploadCaptionMemeSuccessCreateData

---@class Video
---@field action? string
---@field assetId? string
---@field atMs? number
---@field audioAssetId? string
---@field beatOffsetMs? number
---@field bitrateKbps? number
---@field bpm? number
---@field cancelled? boolean
---@field container? string
---@field durationMs? number
---@field durationSeconds number
---@field easing? string
---@field error? string
---@field frameRate? number
---@field inputFormat string
---@field intensity? number
---@field jobId? string
---@field locale? string
---@field mimeType string
---@field name? string
---@field offsetMs? number
---@field outputPresetId string
---@field outputUrl? string
---@field planTier string
---@field presetId string
---@field progressPercent? number
---@field project? table
---@field projectId? string
---@field property? string
---@field sourceDeviceId? string
---@field sourceUrl? string
---@field stage? string
---@field startMs? number
---@field stylePresetId? string
---@field syncToBeatGrid? boolean
---@field tone? string
---@field trackId? string
---@field transcript? string
---@field trendKeywords? table
---@field type? string
---@field updatedAt? string
---@field value? number
---@field watermarkEnabled? boolean
---@field watermarkText? string
---@field workerId? string

---@class VideoLoadMatch
---@field action? string
---@field assetId? string
---@field atMs? number
---@field audioAssetId? string
---@field beatOffsetMs? number
---@field bitrateKbps? number
---@field bpm? number
---@field cancelled? boolean
---@field container? string
---@field durationMs? number
---@field durationSeconds? number
---@field easing? string
---@field error? string
---@field frameRate? number
---@field inputFormat? string
---@field intensity? number
---@field jobId? string
---@field locale? string
---@field mimeType? string
---@field name? string
---@field offsetMs? number
---@field outputPresetId? string
---@field outputUrl? string
---@field planTier? string
---@field presetId? string
---@field progressPercent? number
---@field project? table
---@field projectId? string
---@field property? string
---@field sourceDeviceId? string
---@field sourceUrl? string
---@field stage? string
---@field startMs? number
---@field stylePresetId? string
---@field syncToBeatGrid? boolean
---@field tone? string
---@field trackId? string
---@field transcript? string
---@field trendKeywords? table
---@field type? string
---@field updatedAt? string
---@field value? number
---@field watermarkEnabled? boolean
---@field watermarkText? string
---@field workerId? string

---@class VideoCreateData
---@field action? string
---@field assetId? string
---@field atMs? number
---@field audioAssetId? string
---@field beatOffsetMs? number
---@field bitrateKbps? number
---@field bpm? number
---@field cancelled? boolean
---@field container? string
---@field durationMs? number
---@field durationSeconds number
---@field easing? string
---@field error? string
---@field frameRate? number
---@field inputFormat string
---@field intensity? number
---@field jobId? string
---@field locale? string
---@field mimeType string
---@field name? string
---@field offsetMs? number
---@field outputPresetId string
---@field outputUrl? string
---@field planTier string
---@field presetId string
---@field progressPercent? number
---@field project? table
---@field projectId? string
---@field property? string
---@field sourceDeviceId? string
---@field sourceUrl? string
---@field stage? string
---@field startMs? number
---@field stylePresetId? string
---@field syncToBeatGrid? boolean
---@field tone? string
---@field trackId? string
---@field transcript? string
---@field trendKeywords? table
---@field type? string
---@field updatedAt? string
---@field value? number
---@field watermarkEnabled? boolean
---@field watermarkText? string
---@field workerId? string

local M = {}

return M
