// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/memesio-content-creation-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"agent | agent_infra | ai_caption | ai_job | ai_meme_generation_succeeded | ai_provider | analytics | auth | billing | collaboration | compliance | create_meme | developer_api | free_caption_meme_success | free_template_search | generate | growth | list_meme | media | meme | public_template_media_item | standalone_agent_bootstrap | template | template_search | trend_alert | upload_caption_meme_success | video"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.MemesioContentCreationSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "memesio-content-creation_list",
		Description: "List records from MemesioContentCreation. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "memesio-content-creation_load",
		Description: "Load a single record from MemesioContentCreation. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.MemesioContentCreationSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.MemesioContentCreationSDK, name string) (sdk.MemesioContentCreationEntity, error) {
	switch strings.ToLower(name) {
	case "agent":
		return client.Agent(nil), nil
	case "agent_infra":
		return client.AgentInfra(nil), nil
	case "ai_caption":
		return client.AiCaption(nil), nil
	case "ai_job":
		return client.AiJob(nil), nil
	case "ai_meme_generation_succeeded":
		return client.AiMemeGenerationSucceeded(nil), nil
	case "ai_provider":
		return client.AiProvider(nil), nil
	case "analytics":
		return client.Analytics(nil), nil
	case "auth":
		return client.Auth(nil), nil
	case "billing":
		return client.Billing(nil), nil
	case "collaboration":
		return client.Collaboration(nil), nil
	case "compliance":
		return client.Compliance(nil), nil
	case "create_meme":
		return client.CreateMeme(nil), nil
	case "developer_api":
		return client.DeveloperApi(nil), nil
	case "free_caption_meme_success":
		return client.FreeCaptionMemeSuccess(nil), nil
	case "free_template_search":
		return client.FreeTemplateSearch(nil), nil
	case "generate":
		return client.Generate(nil), nil
	case "growth":
		return client.Growth(nil), nil
	case "list_meme":
		return client.ListMeme(nil), nil
	case "media":
		return client.Media(nil), nil
	case "meme":
		return client.Meme(nil), nil
	case "public_template_media_item":
		return client.PublicTemplateMediaItem(nil), nil
	case "standalone_agent_bootstrap":
		return client.StandaloneAgentBootstrap(nil), nil
	case "template":
		return client.Template(nil), nil
	case "template_search":
		return client.TemplateSearch(nil), nil
	case "trend_alert":
		return client.TrendAlert(nil), nil
	case "upload_caption_meme_success":
		return client.UploadCaptionMemeSuccess(nil), nil
	case "video":
		return client.Video(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
